apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app
  namespace: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
        - name: tabeldata-oauth2-resource-server
          image: tabeldata.ip-dynamic.com:8087/tabeldata/tabeldata-oauth2-resource-server:1.0.1-release
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 9090
          envFrom:
            - configMapRef:
                name: api-config
          command:
            - "java"
            - "-jar"
            - "-Djava.security.egd=file:/dev/./urandom"
            - "/tabeldata-oauth2-resource-server.jar"
          args:
            - "--DATABASE_HOST=$(DATABASE_HOST)"
            - "--DATABASE_PORT=$(DATABASE_PORT)"
            - "--DATABASE_USER=$(DATABASE_USER)"
            - "--DATABASE_PASSWORD=$(DATABASE_PASSWORD)"
            - "--DATABASE_NAME=$(DATABASE_NAME)"
            - "--AUTHTORIZATION_SERVER_HOST=$(AUTHTORIZATION_SERVER_HOST)"
            - "--AUTHTORIZATION_SERVER_PORT=$(AUTHTORIZATION_SERVER_PORT)"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: api
  labels:
    app: api-app
data:
  DATABASE_HOST: "api-db-service"
  DATABASE_PORT: "5432"
  DATABASE_USER: "tabeldata_resource_server"
  DATABASE_PASSWORD: "tabeldata_resource_server"
  DATABASE_NAME: "tabeldata_resource_server"
  AUTHTORIZATION_SERVER_HOST: "auth-service.auth"
  AUTHTORIZATION_SERVER_PORT: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: api
spec:
  selector:
    app: api-app
  ports:
    - port: 9090
      targetPort: 9090
      protocol: "TCP"
